services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: realtimechat-backend
        volumes:
            - .:/app
        ports:
            - '3001:3001'
        environment:
            DB_HOST: 'db'
            DB_USER: 'postgres'
            DB_PASSWORD: 'testdb'
            DB_NAME: 'chatdb'
            DB_PORT: 5432
            PORT: 3001
            CACHE_PORT: 6379
            CACHE_HOST: cache
        depends_on:
            db:
                condition: service_started
            cache:
                condition: service_started
    ui:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        container_name: realtimechat-frontend
        volumes:
            - ../frontend:/app
        ports:
            - '5173:5173'
        depends_on:
            - api
    db:
        image: postgres:17-alpine
        container_name: realtimechat-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: testdb
            POSTGRES_DB: chatdb
        ports:
            - '5432:5432'
        volumes:
            - pg_data:/var/lib/postgresql/data
    cache:
        container_name: realtimechat-cache
        image: valkey/valkey:8-alpine3.22
        ports:
            - '6379:6379'

volumes:
    pg_data:
